// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwx4pbOLth8Gv2T-EvbkrXt74_J4MnfTk',
    appId: '1:280982943527:web:22efbf70badd394adf5b02',
    messagingSenderId: '280982943527',
    projectId: 'flutterinclass',
    authDomain: 'flutterinclass.firebaseapp.com',
    storageBucket: 'flutterinclass.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvZUOGvc0W86ue7Ssamo-xCzMai5V2yk',
    appId: '1:280982943527:android:bc0eecdbf5c2d9c9df5b02',
    messagingSenderId: '280982943527',
    projectId: 'flutterinclass',
    storageBucket: 'flutterinclass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWC3vVnZKlR-1RspCf_P0339AkBbStUac',
    appId: '1:280982943527:ios:f2b4980fc9202023df5b02',
    messagingSenderId: '280982943527',
    projectId: 'flutterinclass',
    storageBucket: 'flutterinclass.appspot.com',
    iosClientId: '280982943527-2fslo3amcb0qniq6ugr0p7pfaaqrfs65.apps.googleusercontent.com',
    iosBundleId: 'com.example.inclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWC3vVnZKlR-1RspCf_P0339AkBbStUac',
    appId: '1:280982943527:ios:f2b4980fc9202023df5b02',
    messagingSenderId: '280982943527',
    projectId: 'flutterinclass',
    storageBucket: 'flutterinclass.appspot.com',
    iosClientId: '280982943527-2fslo3amcb0qniq6ugr0p7pfaaqrfs65.apps.googleusercontent.com',
    iosBundleId: 'com.example.inclass',
  );
}
